# Generated by Django 5.2.10 on 2026-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_external_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='enviopack_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_option_data',
            field=models.JSONField(blank=True, help_text='Datos del servicio de correo elegido', null=True),
        ),
    ]
