# Generated by Django 5.2.10 on 2026-01-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShopConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Mi Tienda', max_length=255)),
                ('primary_color', models.CharField(default='#FF5733', help_text='Formato Hex: #RRGGBB', max_length=7)),
                ('secondary_color', models.CharField(blank=True, default='#333333', max_length=7)),
                ('logo_url', models.URLField(blank=True, max_length=500, null=True)),
                ('social_links', models.JSONField(blank=True, default=dict, help_text='Ej: {"instagram": "@tienda", "whatsapp": "+549..."}')),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('mp_public_key', models.CharField(blank=True, max_length=255)),
                ('mp_access_token', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Configuración de Tienda',
                'verbose_name_plural': 'Configuración de Tienda',
            },
        ),
    ]
