# Generated by Django 5.2.10 on 2026-01-25 04:28

import encrypted_model_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopconfig',
            name='mp_access_token',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shopconfig',
            name='mp_public_key',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True),
        ),
    ]
