"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dj_database_url import config
import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

FIELD_ENCRYPTION_KEY = os.getenv("FIELD_ENCRYPTION_KEY")

if not FIELD_ENCRYPTION_KEY:
    raise RuntimeError("FIELD_ENCRYPTION_KEY no definida")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

#ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')
ALLOWED_HOSTS = ["*"]
AUTH_USER_MODEL = 'users.User'

LOGIN_URL = '/admin/login/'

# Application definition

INSTALLED_APPS = [
    # Jazzmin admin interface (MUST come before django.contrib.admin)
    'jazzmin',
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # ... cloudinary ...
    'cloudinary_storage',
    'cloudinary',
    # ... cors ...
    'corsheaders',
    'rest_framework',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'django_filters',

    # ... apps de django ...
    'apps.users',
    'apps.catalog',
    'apps.orders',
    #'apps.payments',
    'apps.core',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', # <--- Ponlo lo más arriba posible

    'django.middleware.security.SecurityMiddleware',
    "whitenoise.middleware.WhiteNoiseMiddleware",
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": dj_database_url.config(
        conn_max_age=0, #Cambiar al llevar a produccion
        ssl_require=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Authentication backends - permite login con email o username
AUTHENTICATION_BACKENDS = [
    'apps.users.authentication.EmailBackend',
    'django.contrib.auth.backends.ModelBackend',
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"
# ============================================================================
# MEDIA FILES & CLOUDINARY CONFIGURATION
# ============================================================================

# Media files (User uploads)

# Cloudinary Configuration
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
    'SECURE': True,  # Use HTTPS URLs
    'STATIC_IMAGES_EXTENSIONS': ['jpg', 'jpeg', 'png', 'gif', 'svg', 'webp'],
}

# Use Cloudinary if credentials are configured, otherwise use local storage
# AGREGA ESTO EN SU LUGAR:
DEBUG = os.getenv('DEBUG', 'False') != 'True'  # Usar Cloudinary solo en producción
if not DEBUG and os.getenv('CLOUDINARY_CLOUD_NAME'):
    STORAGES = {
        "default": {
            "BACKEND": "cloudinary_storage.storage.MediaCloudinaryStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }
else:
    STORAGES = {
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
    }

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'apps.users.authentication.CookieJWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
        'rest_framework.parsers.FormParser',
        'rest_framework.parsers.MultiPartParser',
    ),
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
}

CORS_ALLOW_ALL_ORIGINS = True
# Allow frontend URLs for CORS (includes ngrok for development)
CORS_ALLOWED_ORIGINS = [
    "https://tnr9tkbevq3i.share.zrok.io",
    "https://web-production-ca959.up.railway.app",
]
CORS_ALLOW_CREDENTIALS = True

# CSRF & Cookie settings for API with HttpOnly JWT
CSRF_TRUSTED_ORIGINS = [
    "https://tnr9tkbevq3i.share.zrok.io",
    "https://web-production-ca959.up.railway.app",
]
# Add ngrok URL if configured

# When using ngrok: Backend is HTTPS (ngrok), Frontend is HTTP (localhost)
# Cookies REQUIRE: secure=True (HTTPS endpoint) and SameSite=None (cross-origin)
SESSION_COOKIE_DOMAIN = None

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SAMESITE = 'None'
CSRF_COOKIE_SAMESITE = 'None'
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")


if not DEBUG:
    # Seguridad adicional para producción
    SECURE_HSTS_SECONDS = 31536000  # 1 año
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True

# ============================================================================
# EMAIL CONFIGURATION (RESEND)
# ============================================================================
RESEND_API_KEY = os.getenv('RESEND_API_KEY')
EMAIL_FROM = os.getenv('EMAIL_FROM', 'Mi Tienda <no-reply@mitienda.com>')
PASSWORD_RESET_URL = os.getenv('PASSWORD_RESET_URL', 'https://localhost:3000/reset-password')
PASSWORD_RESET_TOKEN_EXPIRE_MINUTES = 30  # Token válido por 30 minutos

# ============================================================================
# JAZZMIN ADMIN CONFIGURATION
# ============================================================================

JAZZMIN_SETTINGS = {
    "site_title": "Tienda Admin",
    "site_header": "Dashboard de Gestión",
    "site_brand": "Tienda",
    "welcome_sign": "Bienvenido al Dashboard de Gestión de Tienda",
    "copyright": "© 2025 Tienda. All rights reserved.",
    
    # ========== ICONS & BRANDING ==========
    "site_logo": None,  # Set to your logo path if available
    "site_icon": "fas fa-shopping-cart",
    "site_icon_classes": "image-x50",
    
    # ========== NAVIGATION CONFIGURATION ==========
    # Order by importance: Orders > Catalog > Users > Core > Auth
    "order_with_respect_to": [
        "orders",
        "catalog",
        "users",
        "core",
        "auth",
    ],
    
    # ========== APP LIST WITH CUSTOM ICONS ==========
    "app_list": [
        {
            "app": "orders",
            "name": "Ventas",
            "icon": "fas fa-shopping-bag",
            "permissions": ["orders.view_order"],
            "models": [
                {
                    "name": "order",
                    "icon": "fas fa-shopping-bag",
                    "permissions": ["orders.view_order", "orders.add_order", "orders.change_order", "orders.delete_order"],
                },
                {
                    "name": "orderitem",
                    "icon": "fas fa-boxes",
                    "permissions": ["orders.view_orderitem"],
                },
            ],
        },
        {
            "app": "catalog",
            "name": "Catálogo",
            "icon": "fas fa-store",
            "permissions": ["catalog.view_product"],
            "models": [
                {
                    "name": "product",
                    "icon": "fas fa-tshirt",
                    "permissions": ["catalog.view_product", "catalog.add_product", "catalog.change_product", "catalog.delete_product"],
                },
                {
                    "name": "productvariant",
                    "icon": "fas fa-boxes",
                    "permissions": ["catalog.view_productvariant"],
                },
                {
                    "name": "category",
                    "icon": "fas fa-tags",
                    "permissions": ["catalog.view_category", "catalog.add_category", "catalog.change_category", "catalog.delete_category"],
                },
            ],
        },
        {
            "app": "users",
            "name": "Usuarios",
            "icon": "fas fa-users",
            "permissions": ["users.view_user"],
            "models": [
                {
                    "name": "user",
                    "icon": "fas fa-user-circle",
                    "permissions": ["users.view_user", "users.add_user", "users.change_user", "users.delete_user"],
                },
            ],
        },
        {
            "app": "core",
            "name": "Configuración",
            "icon": "fas fa-sliders-h",
            "permissions": ["core.view_shopconfig"],
            "models": [
                {
                    "name": "shopconfig",
                    "icon": "fas fa-cog",
                    "permissions": ["core.view_shopconfig", "core.change_shopconfig"],
                },
            ],
        },
        {
            "app": "auth",
            "name": "Control de Acceso",
            "icon": "fas fa-lock",
            "permissions": ["auth.view_user"],
            "models": [
                {
                    "name": "group",
                    "icon": "fas fa-object-group",
                    "permissions": ["auth.view_group"],
                },
                {
                    "name": "permission",
                    "icon": "fas fa-shield-alt",
                    "permissions": ["auth.view_permission"],
                },
            ],
        },
    ],
    
    # ========== SEARCH CONFIGURATION ==========
    "search_model": ["users.User", "orders.Order"],
    
    # ========== USER-RELATED SETTINGS ==========
    "usersettings_allow_user_preferences": True,
    "show_ui_builder": True,
    
    # ========== DASHBOARD TWEAKS ==========
    "default_icon_parents": "fas fa-chevron-circle-right",
    "default_icon_children": "fas fa-circle",
    
    # ========== SIDEBAR & APPEARANCE ==========
    "sidebar": {
        "navigation": [
            {
                "name": "Ventas",
                "icon": "fas fa-shopping-bag",
                "items": [
                    {
                        "name": "Pedidos",
                        "url": "/admin/orders/order/",
                        "icon": "fas fa-shopping-bag",
                    },
                    {
                        "name": "Elementos de Pedido",
                        "url": "/admin/orders/orderitem/",
                        "icon": "fas fa-boxes",
                    },
                ],
            },
            {
                "name": "Catálogo",
                "icon": "fas fa-store",
                "items": [
                    {
                        "name": "Productos",
                        "url": "/admin/catalog/product/",
                        "icon": "fas fa-tshirt",
                    },
                    {
                        "name": "Variantes",
                        "url": "/admin/catalog/productvariant/",
                        "icon": "fas fa-boxes",
                    },
                    {
                        "name": "Categorías",
                        "url": "/admin/catalog/category/",
                        "icon": "fas fa-tags",
                    },
                ],
            },
            {
                "name": "Usuarios",
                "icon": "fas fa-users",
                "items": [
                    {
                        "name": "Clientes",
                        "url": "/admin/users/user/",
                        "icon": "fas fa-user-circle",
                    },
                ],
            },
            {
                "name": "Tienda",
                "icon": "fas fa-cog",
                "items": [
                    {
                        "name": "Configuración",
                        "url": "/admin/core/shopconfig/",
                        "icon": "fas fa-sliders-h",
                    },
                ],
            },
            {
                "name": "Seguridad",
                "icon": "fas fa-lock",
                "items": [
                    {
                        "name": "Grupos",
                        "url": "/admin/auth/group/",
                        "icon": "fas fa-object-group",
                    },
                ],
            },
        ],
    },
    
    # ========== BUTTON CONFIGURATION ==========
    "show_forms": True,
    "changeform_format": "horizontal_tabs",
    
    # ========== TOP MENU CUSTOMIZATION ==========
    "topmenu_links": [
        {
            "name": "Dashboard",
            "url": "/admin/",
            "permissions": ["auth.view_user"],
            "icon": "fas fa-home",
        },
        {
            "name": "Ver Sitio",
            "url": "/",
            "permissions": ["auth.view_user"],
            "icon": "fas fa-external-link-alt",
            "new_window": True,
        },
    ],
    
    # ========== UI CUSTOMIZATION ==========
    "show_search": True,
    "show_recent": True,
    "changelist_filters_in_modal": True,
    "navigation_expanded": True,
    "hide_apps": [],
    "hide_models": [],
    "custom_css": None,
    "custom_js": None,
    "use_google_fonts_cdn": True,
    "show_administration_panel": True,
}

# ============================================================================
# JAZZMIN UI TWEAKS
# ============================================================================

JAZZMIN_UI_TWEAKS = {
    "navbar_small": False,
    "footer_small": False,
    "body_small": False,
    "brand_small": False,
    "brand_colour": "navbar-dark",
    "navbar": "navbar-dark",
    "accent": "accent-primary",
    "sidebar": "sidebar-dark-primary",
    "sidebar_nav_small_icon": False,
    "sidebar_disable_expand": False,
    "sidebar_nav_child_indent": False,
    "sidebar_nav_compact_style": False,
    "sidebar_nav_legacy_style": False,
    "sidebar_nav_flat_style": False,
    "theme": "darkly",  # Modern, clean theme
    "dark_mode_theme": "darkly",
    "button_classes": {
        "primary": "btn-primary",
        "secondary": "btn-secondary",
        "danger": "btn-danger",
        "warning": "btn-warning",
        "success": "btn-success",
        "info": "btn-info",
    },
}