# Generated by Django 5.2.10 on 2026-02-01 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_productvariant_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_order',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Orden visual (1-4)', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Mostrar en home'),
        ),
    ]
