# Generated by Django 5.2.10 on 2026-02-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_featured_order_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='height',
            field=models.DecimalField(decimal_places=1, default=5.0, help_text='Alto en CM', max_digits=5),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='length',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Largo en CM', max_digits=5),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='weight',
            field=models.DecimalField(decimal_places=3, default=0.1, help_text='Peso en KG', max_digits=6),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='width',
            field=models.DecimalField(decimal_places=1, default=10.0, help_text='Ancho en CM', max_digits=5),
        ),
    ]
